sudo: required
language: node_js
node_js:
- '8'
services:
- docker
- redis
branches:
  only:
  - master
before_install:
- docker run -d -p 9000:9000 --name minio1 -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" minio/minio server /data
- docker run -d --name etcd -p 2380:2380 -p 4001:4001 quay.io/coreos/etcd:latest /usr/local/bin/etcd
  --data-dir=data.etcd --name "my-etcd" --cors='*' --initial-advertise-peer-urls http://0.0.0.0:2380
  --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://0.0.0.0:4001
  --listen-client-urls http://0.0.0.0:4001     --initial-cluster-state new
install:
- npm install
- npm install -g snyk
- snyk test || true
#cache:
#  directories:
#  - node_modules
script:
- NODE_ENV=test npm run-script test-travis
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
after_success:
- |
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis CI"
    git remote set-url --push origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    git remote -v
    git checkout -f -b version-branch
    npm version patch -m "$(git log -1 --pretty=%B) .... bump version [skip ci]"
    git push origin version-branch:master --follow-tags
    docker login --username yehiyam --password ${DOCKER_HUB_PASS}
  else
    echo "version skiped!"
  fi
- snyk monitor
deploy:
  skip_cleanup: true
  provider: script
  script: PRIVATE_REGISTRY=docker.io/hkube npm run build
  on:
    branch: master
after_deploy:
  - curl -X POST -H 'accept:application/json'  -H "authorization:token ${TRAVIS_API_TOKEN}" -H 'content-type:application/json' -H 'travis-api-version:3' -d "{\"request\":{\"branch\":\"master\",\"message\":\"triggered by ${TRAVIS_REPO_SLUG}\"}}" "https://api.travis-ci.org/repo/kube-HPC%2Frelease-manager/requests"
env:
  global:
  - secure: GpfSMsnRcBOcIMWYXpSOtnnaTfqCh8PNJkg21p0vuKFBgrUs+1Im+mKKsCeJIQGNpctNWlFYeTy8adll8NyZoDwjrq1+/FEcUQQXptjknJ7n1lJg8uznXdwCT7bKuc0g5X8XP8RgA5K54q+NnXD/RIXf2/j/IkGR4BVJDZKNRSz52lzNNts9GxRuJQNU4/ZMRLHpCKADNGIMS890uh9Zc5mDw1z2c2+BCJLOGpLKvrG3LqGxQjGuiVDbzOqI/FbSbx7YW1bxP+NgvBGyBZvcUOO3c4ohdaMTlLkGvqSgTojpSw9LIFeoaXw4lkYDG7Lv3q1qwe9+bvPTDpxzQPB5pZ7NX05Pc1rjGPGU5KbKXE8TsNDdvarOF9jG1gbpL+/TWsZhVo91Ji9HEpcFCibaprVBAZXkv87jCGsvSldmkUA7WmQykSOlSCHLMoSIniV/VTrfNQUaAsBlqLUhFMioUqfTfJeuPrA9IpNUdbQreoDtidLYS2T1DnlT+joStRCdyNN9huCoo4ZV86hwvga0uERQoFMnxBLxRa76djIWw+zsL0Fk+CXQRzbwf6tnKwpT4knHk4+AUovbAy6mYbf+vrEVKyFhpod5LH3frEF8liGrzlC+mBmEk42J1F52rxFYaSPa6yVXq6zoUOb6CULl3jL366+EYwDZTIbKpvThSqQ=
  - secure: iqCvvP94+r421I2KDbbXA9EOpxrR76EVWqddGGLrkBS1bJeKna93/BTcy8++Z5Pe+XrdGWKCW1VvBqU/LYQ0fzwCCrqBSRhnG6LfqGrosluyclXooi4GV3KDvx5ee7rgQi9hN1XjiJoMaZfEiu/94DMlH0KZbsdqI5iHyxtFYX85ymjJgi0zkbZKozRjNeFEXMy+gJBlR3mo70cNDo3/CiOD681HaYLDFm/B4olvPdqSG+PBg+UckQdVHAMV/0srN+hNbXgEqL6G3gB39JIdlTqikYiNg5WkptbSR9YqpVO4hVOAijb8LxU5zIhKZWDSCzzSV+glW7ciqMZsNFj38kNWioniaLvNtCaTkMKkEzEUuqFvWZIWeMgCRUngOI41E9cBuaWd9wzFpj2/alVBnNeqSv1KHa71rOpGMSjkZyYtnJv3ZkXruTADTkYDfzmZwGylpz8JZykWTk1Fx5w7jWYoWg324tZDQnxOhJnTAM+uPKwN8BuVR/cgHye/IEysyWVFHj/es2I6sxw9PXHg/or8OHZmr8iwYXjZ00co7roXS8hxClDAklmOwNYWJvfUEXbwYhApuuoMBoe2zIOVo+ceDHbPrTlE4khNpgw8K3nVaM3qBFZmZX1d3/jmKWhldyG4IEs0ANg9rSzjw4GxSeGPJkbPvpAuW483c+KdCCA=
